// Vibely Check — business claim / owner interest flow
(function(){'use strict';
function esc(v){return String(v||'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function show(place){
 let old=document.getElementById('vibelyClaimModal'); if(old)old.remove();
 const name=place?.name||'';
 const placeId=place?.placeId||place?.id||'';
 const modal=document.createElement('div'); modal.id='vibelyClaimModal'; modal.innerHTML=`<div class="vcm-backdrop"><div class="vcm-card"><button class="vcm-close" aria-label="Close">×</button><div class="vcm-kicker">BUSINESS OWNERS</div><h2>Claim your business</h2><p>Tell us who you are and where to reach you. We’ll review your request and follow up about your Vibely Check business profile.</p><form><label>Business name<input name="business" required value="${esc(name)}"></label><label>Your name<input name="owner" required autocomplete="name"></label><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Phone <span>(optional)</span><input name="phone" type="tel" autocomplete="tel"></label><input name="website" tabindex="-1" autocomplete="off" aria-hidden="true" class="vcm-hp"><button class="vcm-submit">Request access</button><div class="vcm-status" role="status" aria-live="polite"></div></form><small>We’ll only use this information to respond to your request.</small></div></div>`;
 const st=document.createElement('style');st.textContent='.vcm-backdrop{position:fixed;inset:0;background:#21142c66;display:grid;place-items:center;padding:18px;z-index:9999}.vcm-card{position:relative;width:min(480px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:24px;box-shadow:0 24px 70px #0003}.vcm-close{position:absolute;right:16px;top:12px;border:0;background:none;font-size:28px;cursor:pointer}.vcm-kicker{font-size:11px;font-weight:900;letter-spacing:.08em;color:var(--accent)}.vcm-card h2{margin:6px 0}.vcm-card p{color:var(--muted);line-height:1.45}.vcm-card label{display:block;font-size:13px;font-weight:700;margin:12px 0}.vcm-card label span{font-weight:400;color:var(--muted)}.vcm-card input{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:12px;border:1px solid #ddd;border-radius:12px;font:inherit}.vcm-hp{position:absolute!important;left:-9999px!important;width:1px!important;height:1px!important;opacity:0!important}.vcm-submit{width:100%;margin-top:8px;border:0;border-radius:999px;padding:13px;background:var(--accent);color:#fff;font-weight:900;cursor:pointer}.vcm-submit:disabled{opacity:.6;cursor:wait}.vcm-status{min-height:18px;margin-top:10px;text-align:center;font-size:12px;color:var(--muted)}.vcm-card small{display:block;color:var(--muted);margin-top:12px;font-size:11px}';document.head.appendChild(st);document.body.appendChild(modal);
 modal.querySelector('.vcm-close').onclick=()=>modal.remove(); modal.querySelector('.vcm-backdrop').onclick=e=>{if(e.target===e.currentTarget)modal.remove()};
 modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('.vcm-submit'),status=form.querySelector('.vcm-status');const d=new FormData(form);button.disabled=true;button.textContent='Sending…';status.textContent='';
   try{const response=await fetch('/api/business-lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessName:d.get('business'),ownerName:d.get('owner'),email:d.get('email'),phone:d.get('phone'),placeId,website:d.get('website')})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok)throw new Error(data.error||'Unable to send request.');
     form.innerHTML='<div style="text-align:center;padding:18px 4px"><div style="font-size:42px">🎉</div><h3 style="margin:8px 0">Request received!</h3><p style="color:var(--muted);line-height:1.5">Thanks for your interest in Vibely Check for Business. We’ll follow up using the information you provided.</p><button type="button" class="vcm-submit">Done</button></div>';form.querySelector('.vcm-submit').onclick=()=>modal.remove();
   }catch(error){button.disabled=false;button.textContent='Request access';status.textContent=error.message||'Something went wrong. Please try again.';}
 };
}
window.VibelyClaim={show};
function wire(){document.querySelectorAll('#vibelyBusinessInterest button').forEach(btn=>{if(btn.dataset.claimWired)return;btn.dataset.claimWired='1';btn.onclick=()=>{const p=window.__vibelyPlaces?.[0]||{};show(p);};});}
setInterval(wire,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
