// Vibely Check — dedicated For Businesses experience
(function(){'use strict';
function open(){
 let old=document.getElementById('vibelyBusinessLanding');if(old){old.hidden=false;return;}
 const wrap=document.createElement('div');wrap.id='vibelyBusinessLanding';wrap.innerHTML='<div class="vbl-back"><div class="vbl-card"><button class="vbl-x" aria-label="Close">×</button><div class="vbl-kicker">VIBELY CHECK FOR BUSINESS</div><h1>Turn customer vibes into business insight.</h1><p class="vbl-lead">Claim your business and get a clearer picture of how customers experience your space.</p><div class="vbl-features"><div><b>🔥 Your Vibely Score</b><span>See how customers are rating the vibe.</span></div><div><b>❤️ Customer vibes</b><span>Understand the moods and experiences people share.</span></div><div><b>📈 Trends</b><span>Spot changes over time and discover your strongest moments.</span></div></div><button class="vbl-claim">Claim Your Business</button><p class="vbl-note">Business dashboard preview · No payment required to request access</p></div></div>';
 const st=document.createElement('style');st.textContent='.vbl-back{position:fixed;inset:0;background:#21142c66;display:grid;place-items:center;padding:18px;z-index:10000}.vbl-card{position:relative;width:min(560px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:28px;padding:28px;box-shadow:0 24px 80px #0003}.vbl-x{position:absolute;right:16px;top:10px;border:0;background:none;font-size:30px;cursor:pointer}.vbl-kicker{font-size:10px;font-weight:900;letter-spacing:.1em;color:var(--accent)}.vbl-card h1{font-size:30px;line-height:1.08;margin:8px 35px 10px 0}.vbl-lead{font-size:15px;line-height:1.5;color:var(--muted);margin:0 0 20px}.vbl-features{display:grid;gap:10px}.vbl-features div{padding:15px;border:1px solid var(--line);border-radius:16px;background:#fff}.vbl-features b,.vbl-features span{display:block}.vbl-features span{font-size:12px;color:var(--muted);margin-top:4px}.vbl-claim{width:100%;margin-top:18px;border:0;border-radius:999px;padding:14px;background:var(--accent);color:#fff;font-weight:900;cursor:pointer}.vbl-note{text-align:center;color:var(--muted);font-size:10px;margin:10px 0 0}@media(max-width:650px){.vbl-card h1{font-size:26px}}@media(min-width:851px){#mobileBusinessCta{display:block!important;max-width:520px;margin:20px auto 0;border:0;border-radius:999px;padding:15px 22px;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff;font-size:16px;font-weight:900;cursor:pointer;box-shadow:0 10px 22px rgba(124,58,237,.16)}#mobileBusinessBenefits{display:grid!important;grid-template-columns:repeat(3,1fr);gap:12px;max-width:760px;margin:18px auto 0;text-align:center;color:#5d5270}#mobileBusinessBenefits div{font-size:13px;line-height:1.35;padding:14px;border:1px solid var(--line);border-radius:16px;background:#fff}#mobileBusinessBenefits b{display:block;font-size:25px;margin-bottom:6px}}';document.head.appendChild(st);document.body.appendChild(wrap);
 wrap.querySelector('.vbl-x').onclick=()=>wrap.remove();wrap.querySelector('.vbl-back').onclick=e=>{if(e.target===e.currentTarget)wrap.remove()};wrap.querySelector('.vbl-claim').onclick=()=>{wrap.remove();window.VibelyClaim?.show((window.__vibelyPlaces&&window.__vibelyPlaces[0])||{});};
}
function nav(){
 const nav=document.querySelector('header nav,nav');
 const canonical=document.getElementById('businessBtn');
 // Keep exactly one desktop For Businesses control: the canonical button from index.html.
 document.querySelectorAll('header nav button, header button').forEach(b=>{
  if(b!==canonical && b.textContent.trim().toLowerCase()==='for businesses')b.remove();
 });
 if(!canonical && nav && !document.getElementById('vibelyForBusinessNav')){const b=document.createElement('button');b.id='vibelyForBusinessNav';b.type='button';b.textContent='For Businesses';b.onclick=open;b.style.cssText='border:0;background:none;font:inherit;font-weight:800;cursor:pointer;padding:8px 10px';nav.appendChild(b);}
 const old=document.getElementById('vibelyMobileBusiness');if(old)old.remove();
}
setInterval(nav,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',nav);else nav();window.VibelyBusiness={open};
})();
