// Vibely Check — business claim / owner interest flow
(function(){'use strict';
function esc(v){return String(v||'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));}
function show(place){
 let old=document.getElementById('vibelyClaimModal'); if(old)old.remove();
 const name=place?.name||'';
 const modal=document.createElement('div'); modal.id='vibelyClaimModal'; modal.innerHTML=`<div class="vcm-backdrop"><div class="vcm-card"><button class="vcm-close" aria-label="Close">×</button><div class="vcm-kicker">BUSINESS OWNERS</div><h2>Claim your business</h2><p>Tell us where to send information about your Vibely Check business profile and analytics.</p><form><label>Business name<input name="business" required value="${esc(name)}"></label><label>Your name<input name="owner" required></label><label>Email<input name="email" type="email" required></label><label>Phone <span>(optional)</span><input name="phone" type="tel"></label><button class="vcm-submit">Request access</button></form><small>We’ll only use this information to respond to your request.</small></div></div>`;
 const st=document.createElement('style');st.textContent='.vcm-backdrop{position:fixed;inset:0;background:#21142c66;display:grid;place-items:center;padding:18px;z-index:9999}.vcm-card{position:relative;width:min(480px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:24px;padding:24px;box-shadow:0 24px 70px #0003}.vcm-close{position:absolute;right:16px;top:12px;border:0;background:none;font-size:28px;cursor:pointer}.vcm-kicker{font-size:11px;font-weight:900;letter-spacing:.08em;color:var(--accent)}.vcm-card h2{margin:6px 0}.vcm-card p{color:var(--muted);line-height:1.45}.vcm-card label{display:block;font-size:13px;font-weight:700;margin:12px 0}.vcm-card label span{font-weight:400;color:var(--muted)}.vcm-card input{display:block;width:100%;box-sizing:border-box;margin-top:6px;padding:12px;border:1px solid #ddd;border-radius:12px;font:inherit}.vcm-submit{width:100%;margin-top:8px;border:0;border-radius:999px;padding:13px;background:var(--accent);color:#fff;font-weight:900;cursor:pointer}.vcm-card small{display:block;color:var(--muted);margin-top:12px;font-size:11px}';document.head.appendChild(st);document.body.appendChild(modal);
 modal.querySelector('.vcm-close').onclick=()=>modal.remove(); modal.querySelector('.vcm-backdrop').onclick=e=>{if(e.target===e.currentTarget)modal.remove()};
 modal.querySelector('form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);const b=d.get('business'),o=d.get('owner'),em=d.get('email'),ph=d.get('phone');const subject=encodeURIComponent('Vibely Check Business Claim Request');const body=encodeURIComponent(`Business: ${b}\nOwner: ${o}\nEmail: ${em}\nPhone: ${ph||'Not provided'}\n\nPlease contact me about claiming this business on Vibely Check.`);window.location.href=`mailto:?subject=${subject}&body=${body}`;modal.remove();};
}
window.VibelyClaim={show};
function wire(){document.querySelectorAll('#vibelyBusinessInterest button').forEach(btn=>{if(btn.dataset.claimWired)return;btn.dataset.claimWired='1';btn.onclick=()=>{const p=window.__vibelyPlaces?.[0]||{};show(p);};});}
setInterval(wire,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
