// Vibely Check — dedicated For Businesses experience
(function(){'use strict';
function open(){
 let old=document.getElementById('vibelyBusinessLanding');if(old){old.hidden=false;return;}
 const wrap=document.createElement('div');wrap.id='vibelyBusinessLanding';wrap.innerHTML='<div class="vbl-back"><div class="vbl-card"><button class="vbl-x" aria-label="Close">×</button><div class="vbl-kicker">VIBELY CHECK FOR BUSINESS</div><h1>Turn customer vibes into business insight.</h1><p class="vbl-lead">Claim your business and get a clearer picture of how customers experience your space.</p><div class="vbl-features"><div><b>🔥 Your Vibe Score</b><span>See how customers are rating the vibe.</span></div><div><b>❤️ Customer vibes</b><span>Understand the moods and experiences people share.</span></div><div><b>📈 Trends</b><span>Spot changes over time and discover your strongest moments.</span></div></div><div class="vbl-plans"><div class="vbl-plan"><div class="vbl-plan-name">FREE</div><strong>Get discovered</strong><p>Claim your listing and access your basic Vibe Score.</p><ul><li>✓ Claimed business badge</li><li>✓ Basic Vibe Score</li><li>✓ Customer vibe overview</li></ul><button class="vbl-claim vbl-free">Claim for free</button></div><div class="vbl-plan vbl-pro"><div class="vbl-plan-name">PRO</div><strong>Turn vibes into growth</strong><p>Unlock the insights that help you understand when and why customers love your space.</p><ul><li>✓ Everything in Free</li><li>✓ Weekly vibe trends</li><li>✓ Peak vibe times</li><li>✓ Detailed customer vibe breakdown</li></ul><button class="vbl-pro-btn" type="button">Join the Pro waitlist</button></div></div><p class="vbl-note">No payment required today · Pro pricing will be shown before launch</p></div></div>';
 const st=document.createElement('style');st.textContent='.vbl-back{position:fixed;inset:0;background:#21142c66;display:grid;place-items:center;padding:18px;z-index:10000}.vbl-card{position:relative;width:min(760px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:28px;padding:28px;box-shadow:0 24px 80px #0003}.vbl-x{position:absolute;right:16px;top:10px;border:0;background:none;font-size:30px;cursor:pointer}.vbl-kicker{font-size:10px;font-weight:900;letter-spacing:.1em;color:var(--accent)}.vbl-card h1{font-size:30px;line-height:1.08;margin:8px 35px 10px 0}.vbl-lead{font-size:15px;line-height:1.5;color:var(--muted);margin:0 0 20px}.vbl-features{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.vbl-features div{padding:15px;border:1px solid var(--line);border-radius:16px;background:#fff}.vbl-features b,.vbl-features span{display:block}.vbl-features span{font-size:12px;color:var(--muted);margin-top:4px}.vbl-plans{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.vbl-plan{padding:19px;border:1px solid var(--line);border-radius:20px;background:#fff}.vbl-plan.vbl-pro{border:2px solid var(--accent);background:linear-gradient(145deg,#fff,#faf5ff)}.vbl-plan-name{font-size:10px;font-weight:900;letter-spacing:.1em;color:var(--accent)}.vbl-plan strong{display:block;font-size:18px;margin:5px 0}.vbl-plan p{font-size:12px;line-height:1.45;color:var(--muted);min-height:36px}.vbl-plan ul{list-style:none;padding:0;margin:12px 0 0;display:grid;gap:7px;font-size:12px}.vbl-claim,.vbl-pro-btn{width:100%;margin-top:15px;border:0;border-radius:999px;padding:13px;font-weight:900;cursor:pointer}.vbl-claim{background:var(--accent);color:#fff}.vbl-pro-btn{background:#21142c;color:#fff}.vbl-note{text-align:center;color:var(--muted);font-size:10px;margin:12px 0 0}@media(max-width:650px){.vbl-card{padding:22px}.vbl-card h1{font-size:26px}.vbl-features,.vbl-plans{grid-template-columns:1fr}.vbl-plan p{min-height:0}}';document.head.appendChild(st);document.body.appendChild(wrap);
 wrap.querySelector('.vbl-x').onclick=()=>wrap.remove();wrap.querySelector('.vbl-back').onclick=e=>{if(e.target===e.currentTarget)wrap.remove()};wrap.querySelector('.vbl-free').onclick=()=>{wrap.remove();window.VibelyClaim?.show((window.__vibelyPlaces&&window.__vibelyPlaces[0])||{});};wrap.querySelector('.vbl-pro-btn').onclick=()=>{wrap.remove();window.VibelyClaim?.show((window.__vibelyPlaces&&window.__vibelyPlaces[0])||{},'pro');};
}
function nav(){const nav=document.querySelector('header nav,nav');const canonical=document.getElementById('businessBtn');document.querySelectorAll('header nav button, header button').forEach(b=>{if(b!==canonical&&b.textContent.trim().toLowerCase()==='for businesses')b.remove();});if(!canonical&&nav&&!document.getElementById('vibelyForBusinessNav')){const b=document.createElement('button');b.id='vibelyForBusinessNav';b.type='button';b.textContent='For Businesses';b.onclick=open;b.style.cssText='border:0;background:none;font:inherit;font-weight:800;cursor:pointer;padding:8px 10px';nav.appendChild(b);}}
setInterval(nav,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',nav);else nav();window.VibelyBusiness={open};})();
