// Vibe Check — live discovery / Trending experience.
// Trend by recent anonymous check-ins, never lifetime star ratings.
(function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const LABELS={'😍':'Loved','😊':'Chill','🔥':'Energetic','😌':'Relaxed','🥳':'Party','😕':'Not my vibe'};
  const TYPES=[['All','✨ All'],['Coffee','☕ Coffee'],['Food','🍽️ Food'],['Nightlife','🌙 Nightlife'],['Family','👨‍👩‍👧 Family']];
  const SCORE={'😍':10,'😊':8.5,'🔥':9,'😌':8,'🥳':9.2,'😕':3};
  let latestPlaces=[];let timer=null;let activeType='All';

  function styles(){
    if(document.getElementById('vibe-discovery-styles'))return;
    const s=document.createElement('style');s.id='vibe-discovery-styles';s.textContent=`
      .trending-panel{margin:22px 0 0;background:#fff;border:1px solid var(--line);border-radius:24px;padding:20px;box-shadow:0 10px 30px #21142c0a;scroll-margin-top:88px}
      .trending-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:15px}.trending-head h2{margin:0;font-size:23px}.trending-head p{margin:5px 0 0;color:var(--muted);font-size:13px;line-height:1.45}.trending-live{display:inline-flex;align-items:center;gap:5px;font-size:10px;font-weight:950;color:#15803d;background:#ecfdf3;border-radius:999px;padding:6px 9px;white-space:nowrap}.trending-live:before{content:'●';font-size:8px}
      .trending-controls{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:15px}.trend-filter{border:1px solid var(--line);background:#fff;border-radius:999px;padding:8px 11px;font-size:12px;font-weight:800;cursor:pointer;color:var(--ink)}.trend-filter.selected{background:var(--ink);color:#fff;border-color:var(--ink)}
      .trending-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.trend-card{border:1px solid var(--line);border-radius:19px;padding:15px;background:linear-gradient(180deg,#fff,#fbf9fc);cursor:pointer;transition:transform .16s ease,box-shadow .16s ease,border-color .16s ease;min-width:0}.trend-card:hover{transform:translateY(-2px);box-shadow:0 12px 30px #21142c12;border-color:#dfd0ee}.trend-rank{font-size:10px;font-weight:950;color:var(--accent);text-transform:uppercase;letter-spacing:.07em}.trend-name{font-size:17px;font-weight:950;margin:7px 0 2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.trend-meta{font-size:11px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.trend-vibe-row{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:13px}.trend-vibe{font-size:31px;line-height:1}.trend-score{font-size:18px;font-weight:950;white-space:nowrap}.trend-label{font-size:13px;font-weight:900;margin-top:6px}.trend-pulse{margin-top:11px;font-size:12px;font-weight:850}.trend-reason{margin-top:10px;padding:9px 10px;border-radius:12px;background:#f7f2fb;font-size:11px;line-height:1.4}.trend-breakdown{display:flex;gap:5px;flex-wrap:wrap;margin-top:9px}.trend-chip{background:#fff;border:1px solid #eee8f0;border-radius:999px;padding:4px 7px;font-size:10px}.trend-empty{padding:17px;border-radius:15px;background:#faf8fb;color:var(--muted);font-size:13px;line-height:1.5}.trend-footer{margin-top:15px;padding-top:12px;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:10px;align-items:center;font-size:11px;color:var(--muted)}.trend-refresh{border:0;background:#f5f1f7;color:var(--ink);border-radius:10px;padding:8px 10px;font-weight:850;cursor:pointer}
      @media(max-width:850px){.trending-grid{grid-template-columns:1fr 1fr}.trending-panel{padding:16px}}@media(max-width:560px){.trending-grid{grid-template-columns:1fr}.trending-head h2{font-size:20px}.trend-card{padding:14px}}
    `;document.head.appendChild(s);
  }
  function panel(){const host=document.getElementById('exploreContent');if(!host)return null;let p=document.getElementById('vibelyTrending');if(!p){p=document.createElement('section');p.id='vibelyTrending';p.className='trending-panel';host.appendChild(p)}return p}
  function capture(){
    if(window.__vibeDiscoveryFetchPatched)return;window.__vibeDiscoveryFetchPatched=true;
    const original=window.fetch.bind(window);
    window.fetch=async function(...args){const response=await original(...args);try{const url=typeof args[0]==='string'?args[0]:args[0]?.url||'';const method=(args[1]?.method||args[0]?.method||'GET').toUpperCase();if(/\/api\/search\?/.test(url)){const clone=response.clone();const data=await clone.json();if(Array.isArray(data?.places)){latestPlaces=data.places.slice(0,20);schedule()}}if(/\/api\/checkin/.test(url)&&method==='POST'&&response.ok)setTimeout(schedule,450)}catch{}return response}
  }
  async function activity(place){if(!place?.id)return {...place,total:0,counts:{},dominant:null};try{const r=await fetch(`/api/checkin?placeId=${encodeURIComponent(place.id)}&_=${Date.now()}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error();return {...place,total:Number(d.total||0),counts:d.counts||{},dominant:d.dominant||null}}catch{return {...place,total:0,counts:{},dominant:null}}}
  function fallback(p){const t=`${p.name||''} ${p.type||''}`.toLowerCase();if(/bar|club|nightlife|brew|lounge/.test(t))return'🔥';if(/coffee|cafe/.test(t))return'😊';if(/restaurant|food|dining|pizza|thai|mexican|burger/.test(t))return'😍';return'😌'}
  function matchesType(place){if(activeType==='All')return true;const t=`${place.name||''} ${place.type||''} ${(place.tags||[]).join(' ')}`.toLowerCase();if(activeType==='Coffee')return /coffee|cafe|bakery/.test(t);if(activeType==='Food')return /restaurant|food|dining|pizza|thai|mexican|burger|bakery/.test(t);if(activeType==='Nightlife')return /bar|club|nightlife|brew|lounge|music/.test(t);if(activeType==='Family')return /family|park|playground|recreation|kids/.test(t);return true}
  function openPlace(place){const cards=[...document.querySelectorAll('.place')];const card=cards.find(el=>el.querySelector('h3')?.textContent?.trim()===String(place.name||'').trim());const button=card?.querySelector('.small-btn');if(button){button.click();return}if(typeof window.openModal==='function'){const index=latestPlaces.findIndex(x=>String(x.id)===String(place.id));if(index>=0)window.openModal(index)}}
  function scoreFor(x){if(!x.total)return null;const weighted=Object.entries(x.counts||{}).reduce((sum,[v,n])=>sum+(SCORE[v]??7)*Number(n||0),0);return Math.round(weighted/x.total*10)/10}
  function reasonFor(x,vibe,pct){if(x.total===1)return`One fresh check-in is setting the signal right now.`;if(vibe==='😕')return`${pct}% of recent signals say this isn't the vibe.`;return`${pct}% of recent check-ins are ${LABELS[vibe]?.toLowerCase()||'on this vibe'}.`}
  async function render(){
    styles();const p=panel();if(!p)return;
    if(!latestPlaces.length){p.innerHTML='<div class="trending-head"><div><h2>🔥 Happening right now</h2><p>Search a place type and city to see live community energy.</p></div><span class="trending-live">LIVE</span></div>';return}
    p.innerHTML='<div class="trending-head"><div><h2>🔥 Happening right now</h2><p>Not reviews. Not stars. Just what people are feeling right now.</p></div><span class="trending-live">LIVE</span></div><div class="trend-empty">Reading the current vibe pulse…</div>';
    const all=await Promise.all(latestPlaces.map(activity));const filtered=all.filter(matchesType);const active=filtered.filter(x=>x.total>0).sort((a,b)=>Number(b.total)-Number(a.total)).slice(0,6);const controls=TYPES.map(([key,label])=>`<button type="button" class="trend-filter ${activeType===key?'selected':''}" data-trend-filter="${key}">${label}</button>`).join('');
    if(!active.length){p.innerHTML=`<div class="trending-head"><div><h2>🔥 Happening right now</h2><p>${activeType==='All'?'Your search has no recent check-ins yet.':'No live check-ins match this category yet.'}</p></div><span class="trending-live">LIVE</span></div><div class="trending-controls">${controls}</div><div class="trend-empty"><b>Someone has to start the pulse.</b><br>Check in at a place and your anonymous vibe can become the first signal.</div><div class="trend-footer"><span>Anonymous activity · rolling 3-hour window</span><button type="button" class="trend-refresh" id="trendRefresh">↻ Refresh</button></div>`}
    else{
      p.innerHTML=`<div class="trending-head"><div><h2>🔥 Happening right now</h2><p>Ranked by fresh community activity — not old ratings.</p></div><span class="trending-live">LIVE</span></div><div class="trending-controls">${controls}</div><div class="trending-grid">${active.map((x,i)=>{const vibe=x.dominant||fallback(x);const entries=Object.entries(x.counts||{}).filter(([v])=>LABELS[v]).sort((a,b)=>Number(b[1])-Number(a[1])).slice(0,3);const top=entries[0];const pct=top?Math.round(Number(top[1])/Math.max(1,x.total)*100):0;const score=scoreFor(x);return `<article class="trend-card" data-id="${esc(x.id)}"><div class="trend-rank">#${i+1} · Trending now</div><div class="trend-name">${esc(x.name||'Local place')}</div><div class="trend-meta">${esc(x.type||'Local place')} · anonymous live signal</div><div class="trend-vibe-row"><div class="trend-vibe">${esc(vibe)}</div><div class="trend-score">${score??'—'}<span style="font-size:10px;color:#77727b"> /10</span></div></div><div class="trend-label">${esc(LABELS[vibe]||'Current vibe')}</div><div class="trend-pulse">⚡ ${x.total} recent check-in${x.total===1?'':'s'}</div><div class="trend-reason"><b>Why it's trending:</b> ${esc(reasonFor(x,top?.[0]||vibe,pct))}</div><div class="trend-breakdown">${entries.map(([v,n])=>`<span class="trend-chip">${esc(v)} ${Number(n)}</span>`).join('')}</div></article>`}).join('')}</div><div class="trend-footer"><span>Anonymous activity · rolling 3-hour window</span><button type="button" class="trend-refresh" id="trendRefresh">↻ Refresh</button></div>`}
    p.querySelectorAll('[data-trend-filter]').forEach(btn=>btn.addEventListener('click',()=>{activeType=btn.dataset.trendFilter;render()}));
    p.querySelectorAll('.trend-card').forEach(card=>card.addEventListener('click',()=>{const place=latestPlaces.find(x=>String(x.id)===String(card.dataset.id));if(place)openPlace(place)}));
    p.querySelector('#trendRefresh')?.addEventListener('click',()=>render());
  }
  function schedule(){clearTimeout(timer);timer=setTimeout(render,250)}
  window.VibeDiscovery={refresh:schedule,render,openPlace};window.VibelyTrending=window.VibeDiscovery;capture();
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
  setInterval(render,60000);
})();
